# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIfVLRU-wPhj_QY54W4fTSOkFUUspOG8
"""

import sys
!{sys.executable} -m pip freeze > requirements.txt

import os
print(os.getcwd())

pip install fastapi uvicorn

pip install --upgrade pip

from fastapi import FastAPI

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from fastapi import FastAPI
# app = FastAPI()
# @app.get("/")
# def home():
#   return{"message":"My fastapi project is ready"}
# @app.get("/student")
# def student():
#   return {"name":"Bilal",
#   "age": 20,
#   "course": "python"}

